# Generated by Django 3.2.4 on 2023-02-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reviews_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
