# Generated by Django 3.2.4 on 2023-02-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
