# Generated by Django 3.2.4 on 2023-03-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_mailing_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
