version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbpostgres
      - DB_USER=dbuser
      - DB_PASS=dbpassword

    command: >
      sh -c "python manage.py makemigrations --noinput && 
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
    restart: always

  database:
    image: postgres:11.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dbpostgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    restart: always

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    restart: always

  worker:
    build:
      context: .
    volumes:
      - ./store:/store
    depends_on:
      - redis
      - web
    command: celery -A celery.app worker -l info
    restart: always

  beat:
    build:
      context: .
    volumes:
      - ./store:/store
    depends_on:
      - redis
      - web
      - worker
    command: celery -A celery.app beat -l info
    restart: always

  flower:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: celery -A celery.app flower

volumes:
  postgres_data:
