# Generated by Django 3.2.4 on 2023-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
