# Generated by Django 3.2.4 on 2023-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230305_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Мужчина'), (1, 'Женщина'), (2, 'Унисекс')], default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.SmallIntegerField(default=2020),
        ),
    ]
